name: CI

on:
  push:
    branches:
      - dev
      - 'feature/**'
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Poetry
        run: pip install poetry
#
#      - name: Configure Poetry to create virtual environment in project
#        run: |
#            poetry config virtualenvs.in-project true

#      - name: Install Poetry
#        uses: snok/install-poetry@v1
#        with:
#          virtualenvs-create: true
#          virtualenvs-in-project: true
#          installer-parallel: true
#
#      - name: Cache Poetry packages
#        uses: actions/cache@v4
#        with:
#          path: ~/.cache/pypoetry
#          key: ${{ runner.os }}-poetry-packages-${{ hashFiles('**/poetry.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-poetry-packages-
#
#      - name: Cache Poetry virtualenv
#        id: cache-deps
#        uses: actions/cache@v4
#        with:
#          path: .venv
#          key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-poetry-${{ matrix.python-version }}-
#            ${{ runner.os }}-poetry-
      - name: Cache Poetry dependencies
        uses: actions/cache@v4
        with:
            path: |
              ~/.cache/pypoetry
              ~/.cache/pip
            key: ${{ runner.os }}-${{ matrix.python-version }}-poetry-${{ hashFiles('poetry.lock') }}
            restore-keys: |
              ${{ runner.os }}-${{ matrix.python-version }}-poetry-
#      - name: Cache Poetry dependencies
#        id: cache-deps
#        uses: actions/cache@v4
#        with:
#          path: ./.venv # Cache the virtual environment located in the project
#          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
#          restore-keys: |
#              ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
            poetry install --no-interaction --no-root -vvv

      - name: Run Ruff check
        run: poetry run ruff check .

      - name: Run mypy check
        run: poetry run mypy .